insert into customer (customerId, firstName, lastName, addr, age, sex) values (1, 'Izak', 'Boomes', 'Suite 67', 1, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (2, 'Ursola', 'Endrighi', 'Apt 813', 2, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (3, 'Elfreda', 'Hedworth', 'Suite 65', 3, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (4, 'Julia', 'Halliburton', '10th Floor', 4, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (5, 'Dael', 'Gimbart', 'Suite 91', 5, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (6, 'Kahlil', 'Wyper', '1st Floor', 6, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (7, 'Elvin', 'McDonand', 'Room 1984', 7, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (8, 'Moll', 'Rockell', 'Room 907', 8, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (9, 'Fairleigh', 'Omond', 'Room 1557', 9, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (10, 'Abra', 'Glencrosche', 'Apt 1169', 10, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (11, 'Madelaine', 'Bassett', 'Room 307', 11, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (12, 'Deloris', 'de Courcey', 'Room 1751', 12, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (13, 'Lance', 'Jirek', 'Room 904', 13, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (14, 'Lionello', 'Bunclark', 'Room 109', 14, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (15, 'Gorden', 'Rewbottom', '15th Floor', 15, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (16, 'Orren', 'Romayn', 'Apt 1556', 16, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (17, 'Jeffry', 'Byway', 'Apt 682', 17, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (18, 'Arnuad', 'Biner', 'Room 914', 18, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (19, 'Seymour', 'Tomkys', 'Room 543', 19, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (20, 'Hetty', 'Emes', 'PO Box 61686', 20, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (21, 'Drusilla', 'Itzik', '16th Floor', 21, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (22, 'Joye', 'Coakley', 'Suite 17', 22, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (23, 'Germain', 'Janew', 'Suite 96', 23, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (24, 'Bamby', 'Bourcq', 'Suite 65', 24, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (25, 'Susannah', 'Alldred', 'Room 779', 25, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (26, 'Wood', 'Ivers', 'Suite 75', 26, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (27, 'Astrid', 'Wenman', 'PO Box 54858', 27, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (28, 'Ravid', 'Klais', 'Suite 16', 28, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (29, 'Elvis', 'Stait', 'Apt 411', 29, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (30, 'Conrad', 'Krammer', 'Suite 45', 30, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (31, 'Sarena', 'Wandrach', 'Room 1306', 31, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (32, 'Cletus', 'Cervantes', 'PO Box 21042', 32, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (33, 'Ruthie', 'Avent', 'Suite 7', 33, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (34, 'Shepherd', 'Daily', 'Apt 1584', 34, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (35, 'Griswold', 'Turfs', 'Room 1472', 35, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (36, 'Eugenie', 'Vyse', 'PO Box 2491', 36, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (37, 'Yard', 'Stirtle', 'Room 1312', 37, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (38, 'Iorgos', 'Sellen', 'PO Box 51544', 38, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (39, 'Marijn', 'Pringley', 'Apt 943', 39, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (40, 'Alexandra', 'Sends', 'Room 1964', 40, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (41, 'Roslyn', 'Santoro', 'PO Box 17392', 41, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (42, 'Ranee', 'Ciccoloi', 'Suite 82', 42, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (43, 'Eydie', 'Ellyatt', '18th Floor', 43, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (44, 'Mikel', 'McNay', 'Apt 1490', 44, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (45, 'Gillie', 'Frewer', 'PO Box 99081', 45, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (46, 'Northrup', 'Cureton', 'Apt 908', 46, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (47, 'Chrisy', 'Schumacher', 'Apt 894', 47, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (48, 'Lucila', 'Snedden', 'Room 4', 48, 'F');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (49, 'Yancy', 'Scamwell', 'Room 357', 49, 'M');
insert into customer (customerId, firstName, lastName, addr, age, sex) values (50, 'Zulema', 'Jutson', 'Suite 82', 50, 'F');
